services:
  app:
    build:
      context: ../..
      dockerfile: src/luciole-humble-l4t-runtime/Dockerfile
    image: ghcr.io/dkuav/luciole-humble-l4t-runtime:latest
    platform: linux/arm64
    user: luciole

    stdin_open: true
    tty: true
