version: '3.8'

services:
  app:
    build:
      context: ../..
      dockerfile: src/luciole-humble-cuda-dev/Dockerfile
    image: ghcr.io/dkuav/luciole-humble-cuda-dev:latest
    user: luciole

    stdin_open: true
    tty: true

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /mnt/wslg:/mnt/wslg

    environment:
      - DISPLAY=${DISPLAY}
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - PULSE_SERVER=${PULSE_SERVER}
