version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: luciole-humble-dev
    user: luciole

    # WSLg socket
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /mnt/wslg:/mnt/wslg

    # WSLg env
    environment:
      - DISPLAY=${DISPLAY}
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - PULSE_SERVER=${PULSE_SERVER}
